---
workingDir: /tmp/pmdgit
git:
  repository: https://github.com/pintergreg/de-bosch-framework.git
  branch: master
  sourceDir: src
pmd:
  rules:
    - Basic
    - Braces
    - Code Size
    - Controversial
    - Design
    - Empty Code
    - Import Statements
    - Java Logging
    - Naming
    - Optimization
    - Strict Exceptions
    - String and StringBuffer
    - Type Resolution
    - Unnecessary
    - Unused Code